global.dataProvider = [
  {
    name: true,
    icon: 'test',
    type_id: 3,
    position: 0,
    menu_id: '{{id}}',
    description: 'name wrong type',
    errorMessage: 'The Name is not valid type',
  },
  {
    icon: 'test',
    type_id: 3,
    position: 0,
    menu_id: '{{id}}',
    description: 'name is missing',
    errorMessage: 'The Name is required',
  },
  {
    name: 'test',
    icon: 'test',
    position: 0,
    menu_id: '{{id}}',
    description: 'type_id is missing',
    errorMessage: 'The Type id is required',
  },
  {
    name: 'test',
    icon: 'test',
    type_id: 3,
    position: 0,
    description: 'memu_id is missing',
    errorMessage: 'The Menu id is required',
  },
  {
    name: 'test',
    icon: 'test',
    type_id: '3',
    position: 0,
    menu_id: '{{id}}',
    description: 'type_id wrong type',
    errorMessage: 'The Type id is not valid type',
  },
  {
    name: 'test',
    icon: 'test',
    type_id: 3,
    position: 0,
    menu_id: true,
    description: 'menu_id wrong type (boolean)',
    errorMessage: 'The Menu id is not valid type',
  },
  {
    name: 'test',
    icon: 'test',
    type_id: 3,
    position: 0,
    menu_id: '3',
    description: 'menu_id wrong type (string)',
    errorMessage: 'The Menu id is not valid type',
  },
  {
    name: 'test',
    icon: 'test',
    type_id: 3,
    position: 0,
    menu_id: '{{id}}',
    anotherField: '',
    description: 'unknown field',
    errorMessage: 'The property anotherField is not allowed',
  },
];
