global.dataProvider = [
  {
    name: 'all is null',
    properties: {
      boolean: null,
      date: null,
      datetime: null,
      decimal: null,
      integer: null,
      itemlink: null,
      itemlinks: null,
      list: null,
      number: null,
      propertylink: null,
      string: null,
      text: null,
      time: null,
      typelink: null,
      typelinks: null,
    },
  },
  {
    name: 'myitem001',
    properties: {
      boolean: true,
      date: null,
      datetime: null,
      decimal: 3.14,
      integer: -100,
      itemlink: 'laptop123',
      itemlinks: ['laptop300', 'antivirusAVG'],
      list: 'myitemlist1',
      number: 42,
      propertylink: 1,
      string: 'little string',
      // eslint-disable-next-line no-multi-str
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vestibulum lorem sed risus ultricies tristique. Tempus quam pellentesque nec nam. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Amet consectetur adipiscing elit pellentesque habitant morbi. In dictum non consectetur a erat. Diam vulputate ut pharetra sit amet aliquam id diam. Laoreet sit amet cursus sit amet dictum sit amet justo. Pretium aenean pharetra magna ac placerat vestibulum. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. In nisl nisi scelerisque eu ultrices vitae auctor. Erat nam at lectus urna duis convallis.\
Quis eleifend quam adipiscing vitae. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim. Facilisis sed odio morbi quis commodo. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Maecenas ultricies mi eget mauris pharetra et ultrices neque ornare. In aliquam sem fringilla ut morbi tincidunt. Quis enim lobortis scelerisque fermentum dui faucibus in ornare. Cras sed felis eget velit aliquet sagittis. Nisi scelerisque eu ultrices vitae auctor eu. Mauris vitae ultricies leo integer malesuada nunc vel risus commodo.\
Aenean sed adipiscing diam donec adipiscing tristique risus nec. Ac placerat vestibulum lectus mauris ultrices eros in cursus. Pellentesque sit amet porttitor eget dolor morbi non arcu risus. A scelerisque purus semper eget. Orci sagittis eu volutpat odio facilisis mauris sit. Egestas integer eget aliquet nibh praesent. At varius vel pharetra vel turpis nunc eget lorem. Velit egestas dui id ornare arcu odio ut. Mattis aliquam faucibus purus in massa tempor nec feugiat nisl. Rhoncus mattis rhoncus urna neque viverra justo. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Laoreet sit amet cursus sit amet dictum sit.\
Mattis aliquam faucibus purus in massa tempor nec. Mauris vitae ultricies leo integer malesuada nunc vel risus. Sodales ut etiam sit amet nisl. Ultricies mi quis hendrerit dolor magna. Est sit amet facilisis magna. Ut etiam sit amet nisl purus in mollis nunc. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam. Aenean sed adipiscing diam donec adipiscing tristique risus. Molestie nunc non blandit massa enim nec. Dictum varius duis at consectetur lorem donec. Cursus eget nunc scelerisque viverra mauris in aliquam sem. Ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Erat velit scelerisque in dictum non. Sit amet mattis vulputate enim nulla aliquet porttitor. Id leo in vitae turpis massa sed elementum. Morbi tincidunt augue interdum velit. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Tempus imperdiet nulla malesuada pellentesque. Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. Magna ac placerat vestibulum lectus mauris ultrices eros.\
Purus gravida quis blandit turpis cursus in. Suspendisse in est ante in. Ut placerat orci nulla pellentesque dignissim enim sit amet. Tristique senectus et netus et malesuada. Lacinia at quis risus sed vulputate odio ut enim blandit. Pretium aenean pharetra magna ac placerat. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat in. Amet facilisis magna etiam tempor orci. Felis imperdiet proin fermentum leo. Ultricies tristique nulla aliquet enim tortor. Diam in arcu cursus euismod quis viverra nibh cras pulvinar. Enim eu turpis egestas pretium aenean pharetra.',
      time: '22:22:09',
      typelink: 3,
      typelinks: [3, 2],
    },
  },
  {
    name: 'myitem002',
    properties: {
      boolean: false,
      date: '2018-05-24',
      datetime: '2018-05-26 10:56:34',
      decimal: 3.1,
      integer: 0,
      itemlink: 'laptop012',
      itemlinks: ['laptop123'],
      list: 'myitemlist2',
      number: 4,
      propertylink: 7,
      string: 'Squadron42',
      text: 'Lorem ipsum',
      time: '22:22:01',
      typelink: 4,
      typelinks: [4, 5],
    },
  },
  {
    name: 'myitem003',
    properties: {
      boolean: false,
      date: '2056-12-12',
      datetime: '1998-01-01 00:00:01',
      decimal: 5.6,
      integer: 3000056,
      itemlink: 'antivirusAvast',
      itemlinks: ['laptop123', 'antivirusAvast', 'antivirusAVG'],
      list: 'itemlist11',
      number: 10,
      propertylink: 7,
      string: 'I don\'t know what to put here, not inspired',
      text: 'In est ante in nibh mauris',
      time: '00:00:01',
      typelink: 5,
      typelinks: [3, 4, 5],
    },
  },
  {
    name: 'myitem004,ok',
    properties: {
      boolean: null,
      date: null,
      datetime: null,
      decimal: null,
      integer: null,
      itemlink: null,
      itemlinks: null,
      list: null,
      number: null,
      propertylink: null,
      string: null,
      text: null,
      time: null,
      typelink: null,
      typelinks: null,
    },
  },
];
